// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_messages.sql

package db

import (
	"context"
	"database/sql"
)

const createGroupMessage = `-- name: CreateGroupMessage :one
INSERT INTO group_messages (group_id, sender_id, type, message) VALUES ($1, $2, $3, $4)
RETURNING id, group_id, sender_id, type, message, created_at
`

type CreateGroupMessageParams struct {
	GroupID  string         `json:"group_id"`
	SenderID sql.NullString `json:"sender_id"`
	Type     string         `json:"type"`
	Message  string         `json:"message"`
}

func (q *Queries) CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) (GroupMessage, error) {
	row := q.db.QueryRowContext(ctx, createGroupMessage,
		arg.GroupID,
		arg.SenderID,
		arg.Type,
		arg.Message,
	)
	var i GroupMessage
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.Type,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMessagesByGroupID = `-- name: GetGroupMessagesByGroupID :many
SELECT id, group_id, sender_id, type, message, created_at FROM group_messages WHERE group_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetGroupMessagesByGroupIDParams struct {
	GroupID string `json:"group_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetGroupMessagesByGroupID(ctx context.Context, arg GetGroupMessagesByGroupIDParams) ([]GroupMessage, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMessagesByGroupID, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMessage
	for rows.Next() {
		var i GroupMessage
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
