// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_users.sql

package db

import (
	"context"
	"database/sql"
)

const addUserToGroup = `-- name: AddUserToGroup :one
INSERT INTO user_groups (user_id, group_id) VALUES ($1, $2)
RETURNING user_id, group_id, added_at
`

type AddUserToGroupParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

type AddUserToGroupRow struct {
	UserID  string       `json:"user_id"`
	GroupID string       `json:"group_id"`
	AddedAt sql.NullTime `json:"added_at"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (AddUserToGroupRow, error) {
	row := q.db.QueryRowContext(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	var i AddUserToGroupRow
	err := row.Scan(&i.UserID, &i.GroupID, &i.AddedAt)
	return i, err
}

const getUserIDInGroup = `-- name: GetUserIDInGroup :one
SELECT user_id FROM user_groups WHERE user_id = $1 AND group_id = $2 AND removed_at IS NULL
`

type GetUserIDInGroupParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) GetUserIDInGroup(ctx context.Context, arg GetUserIDInGroupParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDInGroup, arg.UserID, arg.GroupID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
UPDATE user_groups SET removed_at = CURRENT_TIMESTAMP WHERE user_id = $1 AND group_id = $2
`

type RemoveUserFromGroupParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}
