// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"database/sql"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_id, name, description) VALUES ($1, $2, $3)
RETURNING id, group_id, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	GroupID     string         `json:"group_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.GroupID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, group_id, name, description, created_at, updated_at FROM groups WHERE group_id = $1
`

func (q *Queries) GetGroup(ctx context.Context, groupID string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, groupID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
