// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (AddUserToGroupRow, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) (GroupMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUser(ctx context.Context, id int32) error
	GetGroup(ctx context.Context, groupID string) (Group, error)
	GetGroupMessagesByGroupID(ctx context.Context, arg GetGroupMessagesByGroupIDParams) ([]GroupMessage, error)
	GetUser(ctx context.Context, id int32) (GetUserRow, error)
	GetUserIDInGroup(ctx context.Context, arg GetUserIDInGroupParams) (string, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
